# -*- coding: utf-8 -*-
"""Copy of Physique Transformation Using Image-to-Image Diffusion Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibTNHELTYKciplTcqJ6jVLYgW0OYKxra
"""

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

import torch

print(torch.__version__)
print(torch.cuda.is_available())

import torch
from diffusers import StableDiffusionImg2ImgPipeline
from PIL import Image
import requests
from io import BytesIO
import matplotlib.pyplot as plt

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")

from google.colab import files

uploaded = files.upload()

image_path = list(uploaded.keys())[0]
init_image = Image.open(image_path).convert("RGB")
init_image = init_image.resize((512, 512))

prompt = "studio portrait of an athletic person with a muscular build, neutral expression, realistic human proportions, soft studio lighting, high detail, professional photography style"

output = pipe(
    prompt=prompt,
    image=init_image,
    strength=0.75,
    guidance_scale=7.5,
    num_inference_steps=20
).images[0]

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(init_image)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Transformed Image")
plt.imshow(output)
plt.axis("off")

plt.show()

output.save("result.png")